"""empty message

Revision ID: 9cd0ce9bdd59
Revises: 7bbb4f5f99a8
Create Date: 2024-05-15 01:14:14.981551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd0ce9bdd59'
down_revision: Union[str, None] = '7bbb4f5f99a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'date_created')
    # ### end Alembic commands ###
